.keys:
  .humans:
    - &eljamm           age1zvazxldyjkg5pkxvmjm06ggzx4jcfhj2pqgl4pznjp7mlkl46u3q0x5hkg
    - &phanirithvij     age10mfyxnncp80gvrsllaeac8c4y3vf3dsr2qxmh4q904a8966px36sv3g2zh
    - &imincik          age1xh8cme9wpj0hu26cscpw3x3u3e4re0933dc9v984r9n5jfmjc5lsrjuch5
    - &erethon          age187upwqdte7t0hkyec22jhac357m9y4fkcdvpg9sj5q9mekjupfnqg9a077
    - &jfly             age1meq58vp6967n8zf3nhl9uma8uyxtus6xy6ps800p4uehwm7m3g4s4aa2pe
  .machines:
    - &makemake         age1ewus3xraznqv6xc2ptua2qjqrjyhfd8uugu08wjduushj3uhgqwsqd6vkk

creation_rules:
  - path_regex: makemake/secrets
    key_groups:
      - age:
        - *eljamm
        - *phanirithvij
        - *imincik
        - *erethon
        - *jfly
        - *makemake
  - path_regex: secrets.json
    key_groups:
      - age:
        - *eljamm
        - *phanirithvij
        - *imincik
        - *erethon
        - *jfly
        - *makemake

stores:
  json:
    indent: 2
  json_binary:
    indent: 2
  yaml:
    indent: 2
